// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBBsWVkNxYz9sblVXOcjephkVIp9YEKi0',
    appId: '1:205019151693:android:c7dd631ffb8ac652144b04',
    messagingSenderId: '205019151693',
    projectId: 'ummel-420',
    storageBucket: 'ummel-420.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlxjmMOJN_ErRrrmdpPLJ7yqLiK1imVJY',
    appId: '1:205019151693:ios:25975b1015758575144b04',
    messagingSenderId: '205019151693',
    projectId: 'ummel-420',
    storageBucket: 'ummel-420.appspot.com',
    iosClientId: '205019151693-bnllo2gbus2gq74p9d0k40se6u4adfc9.apps.googleusercontent.com',
    iosBundleId: 'com.ummel.app',
  );
}
